In [1]:
import numpy as np

In [12]:
a = np.random.rand(3, 4)
print(a)

[[ 0.45090739  0.62025541  0.98416405  0.75267548]
 [ 0.25201585  0.32005539  0.64450367  0.09761916]
 [ 0.13408589  0.92824841  0.46274315  0.90570177]]


In [13]:
b = np.random.rand(3,1)
print(b)

[[ 0.07659958]
 [ 0.79836877]
 [ 0.53462164]]


In [9]:
(a*b)

array([[ 0.10376286,  0.51344995,  0.40365633,  0.82620169],
       [ 0.56775866,  0.4386381 ,  0.06429655,  0.14261394],
       [ 0.02849669,  0.30436154,  0.29971836,  0.22502206]])

In [35]:
w = np.random.randint(low = 1, high = 100,size = (4,3))
x = np.random.randint(low = 1, high = 4, size = (5,4))
print(w)
print(x)

[[22 33 78]
 [34 40 18]
 [81 32 87]
 [25 31 89]]
[[3 2 2 2]
 [2 1 1 3]
 [3 2 2 3]
 [3 1 3 1]
 [1 1 1 2]]


In [36]:
out = w[x,:]

In [37]:
out.shape

(5, 4, 3)

In [38]:
out

array([[[25, 31, 89],
        [81, 32, 87],
        [81, 32, 87],
        [81, 32, 87]],

       [[81, 32, 87],
        [34, 40, 18],
        [34, 40, 18],
        [25, 31, 89]],

       [[25, 31, 89],
        [81, 32, 87],
        [81, 32, 87],
        [25, 31, 89]],

       [[25, 31, 89],
        [34, 40, 18],
        [25, 31, 89],
        [34, 40, 18]],

       [[34, 40, 18],
        [34, 40, 18],
        [34, 40, 18],
        [81, 32, 87]]])

In [39]:
out2 = w[x]

In [41]:
out2.shape

(5, 4, 3)

In [42]:
out2

array([[[25, 31, 89],
        [81, 32, 87],
        [81, 32, 87],
        [81, 32, 87]],

       [[81, 32, 87],
        [34, 40, 18],
        [34, 40, 18],
        [25, 31, 89]],

       [[25, 31, 89],
        [81, 32, 87],
        [81, 32, 87],
        [25, 31, 89]],

       [[25, 31, 89],
        [34, 40, 18],
        [25, 31, 89],
        [34, 40, 18]],

       [[34, 40, 18],
        [34, 40, 18],
        [34, 40, 18],
        [81, 32, 87]]])

In [44]:

x = np.array([[ 0,  1,  2],
            [ 3,  4,  5],
            [ 6,  7,  8],
            [ 9, 10, 11]])

In [45]:
x.shape

(4, 3)

In [50]:
rows = np.array([[0, 1],
                  [2, 3]], dtype=np.intp)

In [51]:
rows.shape

(2, 2)

In [52]:
x[rows]

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [53]:
x[rows].shape

(2, 2, 3)

In [54]:
A= np.random.rand(5,4)

In [56]:
a,b,c,d=np.hsplit(A, 4)

In [57]:
a.shape

(5, 1)

In [58]:
b.shape

(5, 1)

In [60]:
d.shape

(5, 1)

In [25]:
y = np.arange(35).reshape(5,7)

In [26]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [31]:
y[1:5:1,::3]

array([[ 7, 10, 13],
       [14, 17, 20],
       [21, 24, 27],
       [28, 31, 34]])

In [28]:
1:5:2

SyntaxError: invalid syntax (<ipython-input-28-aa78870a13c7>, line 1)

In [30]:
np.array([1:5:2])

SyntaxError: invalid syntax (<ipython-input-30-9a0c050c6fc1>, line 1)

In [61]:
a=np.random.rand(1,2)
b=np.random.rand(1,2)
c=a

In [65]:
(a == b).all()

False

In [64]:
a.all()

True

In [66]:
a.shape

(1, 2)

In [68]:
b=np.zeros(a.shape)

In [69]:
b

array([[ 0.,  0.]])

In [70]:
b.shape

(1, 2)

In [71]:
a

array([[ 0.57252755,  0.38328058]])

In [72]:
a=np.random.rand(3,4,5)

In [74]:
a.shape

(3, 4, 5)

In [75]:
a[:,1,:].shape

(3, 5)

In [76]:
a

array([[[ 0.59484746,  0.52258372,  0.61078393,  0.85177248,  0.09182054],
        [ 0.01811635,  0.80221279,  0.34864065,  0.78198546,  0.42445534],
        [ 0.565409  ,  0.38552552,  0.41899255,  0.07675478,  0.57957213],
        [ 0.65947275,  0.41463278,  0.22739912,  0.86771082,  0.5317409 ]],

       [[ 0.21264615,  0.33611993,  0.89509987,  0.86328046,  0.5612715 ],
        [ 0.46758191,  0.29738196,  0.17317478,  0.03078538,  0.32954787],
        [ 0.00324105,  0.29843512,  0.9692797 ,  0.44888609,  0.31543047],
        [ 0.38048198,  0.55009171,  0.77284496,  0.33442358,  0.25762655]],

       [[ 0.43412264,  0.02827113,  0.72198659,  0.12308095,  0.77038261],
        [ 0.32254853,  0.10939598,  0.5760574 ,  0.29347701,  0.59036259],
        [ 0.96663996,  0.047971  ,  0.38196214,  0.60198856,  0.3597749 ],
        [ 0.01009767,  0.43171328,  0.40483473,  0.64884542,  0.34604241]]])

In [77]:
a[:,1,:]

array([[ 0.01811635,  0.80221279,  0.34864065,  0.78198546,  0.42445534],
       [ 0.46758191,  0.29738196,  0.17317478,  0.03078538,  0.32954787],
       [ 0.32254853,  0.10939598,  0.5760574 ,  0.29347701,  0.59036259]])

In [83]:
mask_flat = np.random.randint(0,3,size=(100,))

In [100]:
label_flat = np.random.randint(1,5, size=(100,))

In [101]:
probs = np.random.rand(100,10)

In [102]:
loss = -np.sum(mask_flat * np.log(probs[np.arange(100), label_flat]))

In [103]:
label_flat

array([2, 3, 3, 4, 2, 2, 2, 2, 3, 1, 4, 4, 4, 2, 4, 4, 2, 1, 4, 3, 4, 2, 2,
       4, 4, 4, 3, 4, 4, 2, 4, 1, 3, 1, 3, 4, 4, 1, 1, 1, 2, 4, 1, 4, 4, 2,
       3, 1, 3, 3, 2, 1, 4, 4, 3, 1, 4, 1, 1, 1, 1, 1, 4, 3, 3, 4, 4, 2, 1,
       4, 4, 3, 3, 2, 4, 2, 2, 4, 1, 2, 3, 1, 1, 3, 2, 4, 2, 1, 2, 1, 4, 1,
       2, 3, 1, 2, 1, 3, 1, 3])

In [104]:
probs[np.arange(100), label_flat]

array([ 0.41465286,  0.93406175,  0.34750821,  0.1054345 ,  0.00825942,
        0.21962305,  0.81139953,  0.01155261,  0.14701674,  0.90087107,
        0.29823861,  0.45452563,  0.43364143,  0.77503435,  0.48601755,
        0.26764277,  0.63772334,  0.07723547,  0.07539647,  0.89194061,
        0.45063933,  0.61410142,  0.87722017,  0.31459981,  0.00152137,
        0.11605555,  0.85612286,  0.81493785,  0.14220529,  0.682943  ,
        0.58659284,  0.66167247,  0.6995743 ,  0.7460492 ,  0.96998329,
        0.83868617,  0.5847659 ,  0.35365198,  0.81206693,  0.26747103,
        0.23444493,  0.13182878,  0.72664246,  0.75119562,  0.84780153,
        0.23782185,  0.35472198,  0.06169082,  0.50054648,  0.09205211,
        0.13490044,  0.38860806,  0.2585897 ,  0.43119099,  0.59964312,
        0.41200012,  0.28676601,  0.55110217,  0.5328486 ,  0.1993818 ,
        0.72237674,  0.32108867,  0.70765583,  0.30949215,  0.54115011,
        0.96052655,  0.87693261,  0.50946491,  0.04772315,  0.42

In [91]:
probs.shape

(100, 10)

In [94]:
probs

array([[ 0.22069989,  0.74961172,  0.79530211,  0.78183146,  0.16803495,
         0.38167515,  0.8614896 ,  0.87617332,  0.16445302,  0.41314812],
       [ 0.47200263,  0.94029858,  0.9596859 ,  0.53286129,  0.34550472,
         0.70770054,  0.87831213,  0.88225772,  0.6133479 ,  0.25438288],
       [ 0.70978201,  0.03603945,  0.09643923,  0.44388884,  0.8624805 ,
         0.45198811,  0.50665441,  0.72380933,  0.20903043,  0.33635637],
       [ 0.83336628,  0.3274412 ,  0.93345078,  0.0840343 ,  0.28411972,
         0.78082362,  0.33974629,  0.2466059 ,  0.41153243,  0.61772959],
       [ 0.46673208,  0.36869651,  0.51794385,  0.74392312,  0.81041894,
         0.99108213,  0.83448654,  0.14158009,  0.62232843,  0.20109928],
       [ 0.32869277,  0.40581407,  0.76478634,  0.05637303,  0.28804032,
         0.12474357,  0.88350763,  0.33066109,  0.99301764,  0.10080919],
       [ 0.832262  ,  0.72988954,  0.9668223 ,  0.77446995,  0.89758952,
         0.87587109,  0.26737801,  0.68780571

In [105]:
self.indices = np.asarray(range(data.shape[0]-self.timesteps))

NameError: name 'data' is not defined

In [112]:
a=np.arange(101)

In [113]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [114]:
b=a[:-1]

In [115]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [116]:
c=a[1:]

In [117]:
b = b.reshape(5,20)
c=c.reshape(5,20)

In [119]:
b.shape

(5, 20)

In [120]:
c.shape

(5, 20)

In [130]:
for i in range(5):
    for j in range(20):
        index = np.where(b[i] == c[i][j])
        print(index[0][0])

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


IndexError: index 0 is out of bounds for axis 0 with size 0

In [124]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
        57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
        77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
        97, 98, 99]])

In [125]:
c

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
         34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100]])

In [131]:
# Copyright 2015 The TensorFlow Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Basic word2vec example."""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import collections
import math
import os
import random
from tempfile import gettempdir
import zipfile

import numpy as np
from six.moves import urllib
from six.moves import xrange  # pylint: disable=redefined-builtin
import tensorflow as tf

# Step 1: Download the data.
url = 'http://mattmahoney.net/dc/'


# pylint: disable=redefined-outer-name
def maybe_download(filename, expected_bytes):
  """Download a file if not present, and make sure it's the right size."""
  local_filename = os.path.join(gettempdir(), filename)
  if not os.path.exists(local_filename):
    local_filename, _ = urllib.request.urlretrieve(url + filename,
                                                   local_filename)
  statinfo = os.stat(local_filename)
  if statinfo.st_size == expected_bytes:
    print('Found and verified', filename)
  else:
    print(statinfo.st_size)
    raise Exception('Failed to verify ' + local_filename +
                    '. Can you get to it with a browser?')
  return local_filename


filename = maybe_download('text8.zip', 31344016)


# Read the data into a list of strings.
def read_data(filename):
  """Extract the first file enclosed in a zip file as a list of words."""
  with zipfile.ZipFile(filename) as f:
    data = tf.compat.as_str(f.read(f.namelist()[0])).split()
  return data

vocabulary = read_data(filename)
print('Data size', len(vocabulary))

# Step 2: Build the dictionary and replace rare words with UNK token.
vocabulary_size = 50000


def build_dataset(words, n_words):
  """Process raw inputs into a dataset."""
  count = [['UNK', -1]]
  count.extend(collections.Counter(words).most_common(n_words - 1))
  dictionary = dict()
  for word, _ in count:
    dictionary[word] = len(dictionary)
  data = list()
  unk_count = 0
  for word in words:
    index = dictionary.get(word, 0)
    if index == 0:  # dictionary['UNK']
      unk_count += 1
    data.append(index)
  count[0][1] = unk_count
  reversed_dictionary = dict(zip(dictionary.values(), dictionary.keys()))
  return data, count, dictionary, reversed_dictionary

# Filling 4 global variables:
# data - list of codes (integers from 0 to vocabulary_size-1).
#   This is the original text but words are replaced by their codes
# count - map of words(strings) to count of occurrences
# dictionary - map of words(strings) to their codes(integers)
# reverse_dictionary - maps codes(integers) to words(strings)
data, count, dictionary, reverse_dictionary = build_dataset(vocabulary,
                                                            vocabulary_size)
del vocabulary  # Hint to reduce memory.
print('Most common words (+UNK)', count[:5])
print('Sample data', data[:10], [reverse_dictionary[i] for i in data[:10]])

data_index = 0

# Step 3: Function to generate a training batch for the skip-gram model.
def generate_batch(batch_size, num_skips, skip_window):
  global data_index
  assert batch_size % num_skips == 0
  assert num_skips <= 2 * skip_window
  batch = np.ndarray(shape=(batch_size), dtype=np.int32)
  labels = np.ndarray(shape=(batch_size, 1), dtype=np.int32)
  span = 2 * skip_window + 1  # [ skip_window target skip_window ]
  buffer = collections.deque(maxlen=span)
  if data_index + span > len(data):
    data_index = 0
  buffer.extend(data[data_index:data_index + span])
  data_index += span
  for i in range(batch_size // num_skips):
    context_words = [w for w in range(span) if w != skip_window]
    words_to_use = random.sample(context_words, num_skips)
    for j, context_word in enumerate(words_to_use):
      batch[i * num_skips + j] = buffer[skip_window]
      labels[i * num_skips + j, 0] = buffer[context_word]
    if data_index == len(data):
      buffer[:] = data[:span]
      data_index = span
    else:
      buffer.append(data[data_index])
      data_index += 1
  # Backtrack a little bit to avoid skipping words in the end of a batch
  data_index = (data_index + len(data) - span) % len(data)
  return batch, labels

batch, labels = generate_batch(batch_size=8, num_skips=2, skip_window=1)
for i in range(8):
  print(batch[i], reverse_dictionary[batch[i]],
        '->', labels[i, 0], reverse_dictionary[labels[i, 0]])

# Step 4: Build and train a skip-gram model.

batch_size = 128
embedding_size = 128  # Dimension of the embedding vector.
skip_window = 1       # How many words to consider left and right.
num_skips = 2         # How many times to reuse an input to generate a label.
num_sampled = 64      # Number of negative examples to sample.

# We pick a random validation set to sample nearest neighbors. Here we limit the
# validation samples to the words that have a low numeric ID, which by
# construction are also the most frequent. These 3 variables are used only for
# displaying model accuracy, they don't affect calculation.
valid_size = 16     # Random set of words to evaluate similarity on.
valid_window = 100  # Only pick dev samples in the head of the distribution.
valid_examples = np.random.choice(valid_window, valid_size, replace=False)


graph = tf.Graph()

with graph.as_default():

  # Input data.
  train_inputs = tf.placeholder(tf.int32, shape=[batch_size])
  train_labels = tf.placeholder(tf.int32, shape=[batch_size, 1])
  valid_dataset = tf.constant(valid_examples, dtype=tf.int32)

  # Ops and variables pinned to the CPU because of missing GPU implementation
  with tf.device('/cpu:0'):
    # Look up embeddings for inputs.
    embeddings = tf.Variable(
        tf.random_uniform([vocabulary_size, embedding_size], -1.0, 1.0))
    embed = tf.nn.embedding_lookup(embeddings, train_inputs)

    # Construct the variables for the NCE loss
    nce_weights = tf.Variable(
        tf.truncated_normal([vocabulary_size, embedding_size],
                            stddev=1.0 / math.sqrt(embedding_size)))
    nce_biases = tf.Variable(tf.zeros([vocabulary_size]))

  # Compute the average NCE loss for the batch.
  # tf.nce_loss automatically draws a new sample of the negative labels each
  # time we evaluate the loss.
  # Explanation of the meaning of NCE loss:
  #   http://mccormickml.com/2016/04/19/word2vec-tutorial-the-skip-gram-model/
  loss = tf.reduce_mean(
      tf.nn.nce_loss(weights=nce_weights,
                     biases=nce_biases,
                     labels=train_labels,
                     inputs=embed,
                     num_sampled=num_sampled,
                     num_classes=vocabulary_size))

  # Construct the SGD optimizer using a learning rate of 1.0.
  optimizer = tf.train.GradientDescentOptimizer(1.0).minimize(loss)

  # Compute the cosine similarity between minibatch examples and all embeddings.
  norm = tf.sqrt(tf.reduce_sum(tf.square(embeddings), 1, keep_dims=True))
  normalized_embeddings = embeddings / norm
  valid_embeddings = tf.nn.embedding_lookup(
      normalized_embeddings, valid_dataset)
  similarity = tf.matmul(
      valid_embeddings, normalized_embeddings, transpose_b=True)

  # Add variable initializer.
  init = tf.global_variables_initializer()

# Step 5: Begin training.
num_steps = 100001

with tf.Session(graph=graph) as session:
  # We must initialize all variables before we use them.
  init.run()
  print('Initialized')

  average_loss = 0
  for step in xrange(num_steps):
    batch_inputs, batch_labels = generate_batch(
        batch_size, num_skips, skip_window)
    feed_dict = {train_inputs: batch_inputs, train_labels: batch_labels}

    # We perform one update step by evaluating the optimizer op (including it
    # in the list of returned values for session.run()
    _, loss_val = session.run([optimizer, loss], feed_dict=feed_dict)
    average_loss += loss_val

    if step % 2000 == 0:
      if step > 0:
        average_loss /= 2000
      # The average loss is an estimate of the loss over the last 2000 batches.
      print('Average loss at step ', step, ': ', average_loss)
      average_loss = 0

    # Note that this is expensive (~20% slowdown if computed every 500 steps)
    if step % 10000 == 0:
      sim = similarity.eval()
      for i in xrange(valid_size):
        valid_word = reverse_dictionary[valid_examples[i]]
        top_k = 8  # number of nearest neighbors
        nearest = (-sim[i, :]).argsort()[1:top_k + 1]
        log_str = 'Nearest to %s:' % valid_word
        for k in xrange(top_k):
          close_word = reverse_dictionary[nearest[k]]
          log_str = '%s %s,' % (log_str, close_word)
        print(log_str)
  final_embeddings = normalized_embeddings.eval()

# Step 6: Visualize the embeddings.


# pylint: disable=missing-docstring
# Function to draw visualization of distance between embeddings.
def plot_with_labels(low_dim_embs, labels, filename):
  assert low_dim_embs.shape[0] >= len(labels), 'More labels than embeddings'
  plt.figure(figsize=(18, 18))  # in inches
  for i, label in enumerate(labels):
    x, y = low_dim_embs[i, :]
    plt.scatter(x, y)
    plt.annotate(label,
                 xy=(x, y),
                 xytext=(5, 2),
                 textcoords='offset points',
                 ha='right',
                 va='bottom')

  plt.savefig(filename)

try:
  # pylint: disable=g-import-not-at-top
  from sklearn.manifold import TSNE
  import matplotlib.pyplot as plt

  tsne = TSNE(perplexity=30, n_components=2, init='pca', n_iter=5000, method='exact')
  plot_only = 500
  low_dim_embs = tsne.fit_transform(final_embeddings[:plot_only, :])
  labels = [reverse_dictionary[i] for i in xrange(plot_only)]
  plot_with_labels(low_dim_embs, labels, os.path.join(gettempdir(), 'tsne.png'))

except ImportError as ex:
  print('Please install sklearn, matplotlib, and scipy to show embeddings.')
  print(ex)


Found and verified text8.zip
Data size 17005207
Most common words (+UNK) [['UNK', 418391], ('the', 1061396), ('of', 593677), ('and', 416629), ('one', 411764)]
Sample data [5234, 3081, 12, 6, 195, 2, 3134, 46, 59, 156] ['anarchism', 'originated', 'as', 'a', 'term', 'of', 'abuse', 'first', 'used', 'against']
3081 originated -> 5234 anarchism
3081 originated -> 12 as
12 as -> 6 a
12 as -> 3081 originated
6 a -> 195 term
6 a -> 12 as
195 term -> 6 a
195 term -> 2 of
Initialized
Average loss at step  0 :  321.040008545
Nearest to than: stockport, derelict, timed, grab, carbonate, parthia, discern, gustavo,
Nearest to th: franchise, dispelling, endocytosis, cpsu, nikolay, gana, minorities, krzy,
Nearest to up: deepwater, millard, antiochian, aforementioned, lillee, ballast, gauntlet, sore,
Nearest to when: pity, cimmerians, hutterite, plebiscite, exploitable, epigrams, overlook, regnant,
Nearest to war: fatale, musculus, cooler, mosfet, manometer, apple, holly, guilds,
Nearest to often: slit

Average loss at step  46000 :  5.22797923934
Average loss at step  48000 :  5.23233724272
Average loss at step  50000 :  4.99865053856
Nearest to than: or, and, gustavo, sponsor, discern, oriental, parthia, devastated,
Nearest to th: eight, seven, seljuk, four, franchise, six, three, nine,
Nearest to up: gauntlet, forbade, him, dasyprocta, rise, deepwater, gnat, them,
Nearest to when: after, and, six, if, while, three, seven, agouti,
Nearest to war: cooler, apple, fatale, disparity, fellow, frequency, jains, computational,
Nearest to often: not, also, still, sometimes, pericles, it, operatorname, there,
Nearest to and: or, operatorname, dasyprocta, eight, agouti, but, six, birkenau,
Nearest to been: by, were, be, publicized, was, cure, are, pitching,
Nearest to its: their, the, his, citing, probability, mathbf, any, diversified,
Nearest to such: ainu, scored, well, vesta, these, conform, kvac, albury,
Nearest to most: works, more, veneration, baldassare, kubrick, liberia, centralized, 

In [132]:
import tensorflow as tf